### ISSUE TITLE
Create a first Docker container

### ISSUE THREAD

**Issue by MichaelPolla** [MichaelPolla/MAMAStress#5]
For example, one that launch a python script.

At the end, we would like to use Docker to make a "pipeline" of the differents steps, so the project has a great modularity.

**Comment by cicciu** [comment]
# Github retriever
## # BUILD DOCKER
$ docker build -t github_retriever_app .
## RUN DOCKER
`$ docker run -e token=2je8dje98ekje0ekje0je... github_retriever_app `
To get file :
``$ docker run -e token=... -v `pwd`/../csv_data:/usr/src/app/csv_data github_retriever_app``

# Jira retriever
## # BUILD DOCKER
$ docker build -t jira_retriever_app .
## RUN DOCKER
`$ docker run jira_retriever_app`
To get file :
``$ docker run -v `pwd`/../csv_data:/usr/src/app/csv_data jira_retriever_app``

**Comment by cicciu** [comment]
### Pass environement variable
http://stackoverflow.com/questions/35766638/how-to-pass-command-line-arguments-to-a-python-script-running-in-docker
